name: example
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dotenv_gen: ^0.0.1

dev_dependencies:
  build_runner: any
  dotenv_gen_runner: 
    path: ../dotenv_gen_runner
  flutter_lints: ^2.0.0

flutter:
