name: dotenv_gen_runner
description: Code generator for dotenv_gen
version: 0.0.2
homepage: https://github.com/North101/dotenv_gen
repository: https://github.com/North101/dotenv_gen

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  analyzer: ^4.0.0
  build: ^2.0.0
  dotenv: ^4.0.0
  dotenv_gen: ^0.0.2
  logging: ^1.0.0
  source_gen: ^1.0.0
  source_helper: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0
  test: any

flutter:
